version: 1.0.{build}
image: Visual Studio 2019

configuration: Release
platform: Any CPU

skip_commits:
  files:
    - '**\*.md'

init:
  - git config --global core.safecrlf false
  - git config --global core.autocrlf input

build_script:
  - ps: .\BuildAll.ps1

artifacts:
- path: ./BuildOutput/VSIX/*.vsix
  name: VSIX Package
